#!/usr/bin/env python3
"""Freeze critical file hashes at build time for tamper detection.

Run this in CI/CD before packaging:
    python freeze_hashes.py > runtime_fence/_frozen_hashes.py

The generated file contains SHA-256 hashes of all critical security modules,
frozen at build time to prevent "living off the land" attacks where an
attacker modifies files before import to bake in tampered hashes.

Copyright (c) 2025 David Cooper
All rights reserved.
"""
import hashlib
import os
import json

CRITICAL_FILES = [
    "runtime_fence.py",
    "hard_kill.py",
    "network_kill.py",
    "bypass_protection.py",
    "fail_mode.py",
    "intent_analyzer.py",
    "behavioral_thresholds.py",
    "task_adherence.py",
    "sliding_window.py",
]


def compute_hashes(base_dir=None):
    """Compute SHA-256 hashes of critical security files.
    
    Args:
        base_dir: Base directory to search for files. Defaults to the directory
                  containing this script.
    
    Returns:
        Dict mapping filename to hash string with 'sha256:' prefix.
    """
    if base_dir is None:
        base_dir = os.path.dirname(os.path.abspath(__file__))
    
    hashes = {}
    for fname in CRITICAL_FILES:
        # Check multiple locations: runtime_fence/ subpackage and current directory
        for search_dir in [os.path.join(base_dir, 'runtime_fence'), base_dir]:
            fpath = os.path.join(search_dir, fname)
            if os.path.exists(fpath):
                try:
                    with open(fpath, 'rb') as f:
                        content = f.read()
                        file_hash = hashlib.sha256(content).hexdigest()
                        hashes[fname] = f"sha256:{file_hash}"
                except (IOError, OSError) as e:
                    print(f"# WARNING: Could not hash {fname}: {e}")
                break
        else:
            print(f"# WARNING: {fname} not found in search paths")
    
    return hashes


if __name__ == '__main__':
    hashes = compute_hashes()
    
    print("# AUTO-GENERATED by freeze_hashes.py — do not edit manually")
    print("# Frozen hashes for tamper detection (generated at build time)")
    print(f"FROZEN_HASHES = {json.dumps(hashes, indent=2)}")
