# AUTO-GENERATED by freeze_hashes.py - do not edit manually
# Frozen hashes for tamper detection (generated at build time)
FROZEN_HASHES = {
  "runtime_fence.py": "sha256:4bcb64bd19b8e2ea7c580c91281ab438cffffe82031a6601374adb25f93a14af",
  "hard_kill.py": "sha256:4335e179ecc1662fb529169313a998b2e7ecc8f3a96f0561a728852f306fc547",
  "network_kill.py": "sha256:1c5fae573aa048e3266719a143d6816e304d8fcd8df6b42887e5b8fe783751e2",
  "bypass_protection.py": "sha256:5a4ff17b7e6a954817967ef8a4edafe274b47bf7c0c80362ef390d3c296f1fdb",
  "fail_mode.py": "sha256:454dab60d93beefb367efa9e7e04493ff5436c33652bf019c21f8093f1c5da70",
  "intent_analyzer.py": "sha256:21e77fb100e3b67b2f13ba55dae6c5e6f48d3f9f2164bc250a15bd7791903a13",
  "behavioral_thresholds.py": "sha256:6893aa38c5bc999e9a0c2983c8df43ac8fe75cd4a2fc8744d3f17d76a9ade001",
  "task_adherence.py": "sha256:ac742d290899b07142ded35001a2184f69ce7c8a2ca47de7561768b60b2186e9",
  "sliding_window.py": "sha256:f0dae5047e1929f829f6ee322383dce5b45786553acba307c593931ab2a4f051"
}
